# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'News' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for News
  #pod 'SDWebImage' , '~> 3.8.2’
  pod 'YYKit'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'MBProgressHUD'
  pod 'YTKKeyValueStore'
  pod 'AFNetworking', '~> 3.0'
end
